### ISSUE TITLE
Allow node re-join with the same key

### ISSUE THREAD

**Issue by maqi** [maidsafe/sn_routing#2214]
To follow the part of the node age rfc , consider to implement :
Allow an offline node restart with the same keys (vaults will have stored these and passed them back to routing). But when it does, we relocate it with age/2, unless it’s less than age 9. If its age is less than 9, just forget the node existed (i.e. restart with the same keys is not allowed).

A suggested approach will be like:
1. Node sends us JoinRequest
2. We check whether we already have that node in members
3. If we do and it is in Left state, we fetch its age
4. If age/2 > 4, we send it the Relocate message with the halved age. As the relocation destination, we can use its current name (so it would rejoin our section) or hash of the name (so it would rejoin some random section)

It is suggested to make the `left members` a `separated bounded container`, and could use an LRU cache having a size limit like 1000 as a startup.

**Comment by dirvine** [comment]
Cool, so far we have as a goal
1. orswat => Joined Nodes
2. Orswat -> offline nodes
Relocated nodes are just really deletes in these 2. The issue is pruning 2 so we don't grow forever.
Then
Improve ways to pass keys to routing or pass form routing to vaults to allow vaults to restart with same keys. Also consider routing generates keys internally for relocate (age++) so adds a bit of complexity there

for nodes with age/2<=4 we can just not add them to the Left/Offline container.
