### ISSUE TITLE
In `minimal` example, peer does not reconnect after control-C and restart

### ISSUE THREAD

**Issue by trevyn** [maidsafe/sn_routing#2307]
**Describe the bug**
Peer does not reconnect after control-C and restart

**To Reproduce**
On "server": `cargo run --example minimal -- -f -i <server ip>`
On "client": `cargo run --example minimal -- -b <server ip>:12000`
...works correctly; `member joined - name: c102c4..` etc...
On client: control-C and re-run same command

**Expected behavior**
Client reconnects to server

**Actual behavior**
Server: `ERROR sn_routing::routing::comm: Sending message to <client ip>:12000 failed: Stream write error`
Client: stuck at `INFO minimal: Node #0 starting...`.

Control-C client and restarting it leads to same problem.
Control-C server and restarting it lets things work again.

**Comment by dirvine** [comment]
Thanks for this. I will ask @madadam  to check it out on Monday.

**Comment by madadam** [comment]
This is actually expected. The problem is that when the second node joins, it is promoted to elder so there are now two elders in total. Then when it leaves, the first node detects it and tries to vote it as offline. But as it is now the only node in the section, it doesn't have a majority so the vote never reaches agreement. Thus it still thinks the section has two elders. Now when the second node joins again, the existing elders need to vote it online. But again, there is only one elders out of two, so the vote never reaches agreement and the joining stalls.

So this is actually a simple instance of a more complex problem which is that we can never lose majority of elders before we select their replacements. We are aware of this and plan to fix it at some point, it just hasn't been a priority. 

What you can try instead is spin up three (or more) nodes, then kill one and start it again. Everything should work correctly in that case.

**Comment by trevyn** [comment]
Ahh interesting. This makes sense and I agree that this is low priority. Thanks!😃
